name: Pint

on:
  push:
    paths:
      - '**.php'
      - 'pint.json'

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
=======
      - uses: actions/checkout@v7
>>>>>>> be7d0c3 (.)

      - name: Setup PHP
        uses: shivammathur/setup-php@latest
        with:
          php-version: '8.3'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@latest

      - name: Run Pint
<<<<<<< HEAD
        run: ./vendor/bin/pint --test
=======
        run: ./vendor/bin/pint --test
>>>>>>> be7d0c3 (.)
