name: Semantic Versioning

on:
  push:
    branches:
      - main
    paths:
      - 'Modules/Media/**'

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
=======
      - uses: actions/checkout@v7
>>>>>>> be7d0c3 (.)
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: Modules/Media/v
<<<<<<< HEAD
          release_branches: main
=======
          release_branches: main
>>>>>>> be7d0c3 (.)
